### ISSUE TITLE
Implement `LogBox` Component(s)

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/blocks#10]
![image](https://user-images.githubusercontent.com/57259/162029492-ab260c46-1cd4-4940-a07d-3178cea7d114.png)

**Comment by oleg-serf** [comment]
@patrickdevivo 
This should be component?
I think this can be implemented on UI.

**Comment by patrickdevivo** [comment]
@oleg-serf  yes, let's implement it as a simple component as it will likely be reused in some different contexts. The `Copy` button behavior will also be worth having as a part of the component
