### ISSUE TITLE
Use `@floating-ui` for hover/floating UI interactions

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/blocks#42]
We have a couple of components here that require "floating" interactions:

- Tooltip
- Menu hovers
- Sidebar hovers

Let's adopt https://floating-ui.com/ as our consistent base for these interactions.

**Comment by german-mergestat** [comment]
To complete this task it is needed:

- [ ] Use `floating-ui` in Tooltip component.
- [ ] Use `floating-ui` in Button component when it has tooltip property.
- [ ] Create new component `HoverCard` using `floating-ui`.
- [ ] Replace `Dropdown`  with sub nav inside `Sidebar.Item` component with new hover card.
