### ISSUE TITLE
Add UI support for a "close" button on tabs

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/blocks#85]
![image](https://user-images.githubusercontent.com/57259/212695249-0244b3e7-a631-473c-8009-a6653b8e734e.png)

In this use case for example, the user should be able to close tabs (i.e. remove them from the UI) since they were able to add them in the first place. I think we need some room for an `x` button or similar in the tab, perhaps to the right of the title?

**Comment by emilyvandewalle** [comment]
I would add an `x` button on the right side indeed, let me know if you want me to provide the UI for this in `blocks` @german-mergestat @patrickdevivo

![image](https://user-images.githubusercontent.com/36261498/212915383-b42a3e5b-80bb-4406-a2e0-c24a202ebbd6.png)
([Figma reference](https://www.figma.com/file/Y0yxXgnubJc2wrQK22xHVo/MergeStat---Data-visualizations?node-id=101%3A4368&t=Ahf01vAHCHDblVk4-1))

**Comment by patrickdevivo** [comment]
@emilyvandewalle - yes, do you mind implementing that button here in `blocks`? And then @german-mergestat can make use of it in `mergestat` for closing out the tabs
